### ISSUE TITLE
不在docker中调试，直接启动单个微服务报错？

### ISSUE THREAD

**Issue by JiangJiaqi90** [liuhll/Surging.Sample#10]
在Program.cs 的host.Run(）时报错
'Surging.Core.CPlatform.Support.IServiceCommandManager' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.”

**Comment by liuhll** [comment]
如果使用`docker-compose`进行调试的话,请对配置文件进行修改。
