### ISSUE TITLE
注册模块组件类型时发生错误：Failed to convert 'MySql}' to type 'Surging.Core.Schedule.Configurations.QuartzClusterDbType'.

### ISSUE THREAD

**Issue by seamusic** [liuhll/Surging.Sample#11]
注册模块组件类型时发生错误：Failed to convert 'MySql}' to type 'Surging.Core.Schedule.Configurations.QuartzClusterDbType'.

感觉MySql}这里怪怪的。
另外，看了其它ISSUE，提到consul的端口号是18500，我使用的是默认的8500。不知是不是这个问题导致的。
当然，我也搜不到18500在哪里设置的。
![微信截图_20190607223500](https://user-images.githubusercontent.com/172009/59112147-0172f200-8975-11e9-9a0f-9b556d0872f6.png)

**Comment by liuhll** [comment]
你需要通过sql脚本创建数据库,请仔细阅读`RADME.md`
