### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gxlqssjf** [liuhll/Surging.Sample#13]
![image](https://user-images.githubusercontent.com/1277598/59587804-b2695180-9118-11e9-8f36-9f0eaa971eee.png)
没有上传相应的nuget包,又默认生成一个Nuget源管理地址:XXX\Surging.Sample\./nupkg

**Comment by liuhll** [comment]
你需要先对surging的组件进行打包,进入到nupkg目录，通过pack.ps1的脚本打包Surging组件
```
cd ./nupkg
./pack.ps1
```
如何启动项目`RADME.md`上有建议，请仔细阅读

**Comment by gxlqssjf** [comment]
是打包全部Surging组件,是不是要打包的内容如下图:
![image](https://user-images.githubusercontent.com/1277598/59816144-913d7680-934d-11e9-82bb-b6d6983bce11.png)

**Comment by liuhll** [comment]
亲 这个不是我的项目呀 😭
