### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by luoyunchong** [liuhll/Surging.Sample#2]
Surging.Core.CPlatform中的ContainerBuilderExtensions.cs中的一个RegisterInstanceByConstraint方法，请问是自己扩展的吗。他实现了继承这二个接口类ISingletonDependency、ITransientDependency的注入，因为我在Surging项目中没有找到这ISingletonDependency、ITransientDependency这二个接口。

**Comment by liuhll** [comment]
是的 是自己扩展的，是一个标识接口，用来向Ioc容器中注册服务组件

**Comment by luoyunchong** [comment]
好的，多谢。。 @liuhll
