### ISSUE TITLE
请问怎么不用Surging最新版本呢

### ISSUE THREAD

**Issue by bingbingtalk** [liuhll/Surging.Sample#3]
请问怎么不用Surging 1.0+呢？0.5.0-bate.6这个版本能用于生产环境吗？

**Comment by liuhll** [comment]
该版本号是我自己定义的,是在作者Surging1.0的源码做了些修改的,你可以修改[这里](https://github.com/liuhll/Surging.Sample/blob/1191bce68381e8442d4cd106765e2e49daaff04c/common.props#L3)指定Surging组件的版本号,至于是否可以使用在生产环境中，因为我对源码做了些修改，你得自己评估

**Comment by bingbingtalk** [comment]
了解，谢谢！
