### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by gxlqssjf** [liuhll/Surging.Sample#4]
![image](https://user-images.githubusercontent.com/1277598/56858489-489cb900-69ad-11e9-80ae-f1f3df0117f8.png)

**Comment by liuhll** [comment]
![image](https://user-images.githubusercontent.com/16488441/56859224-5f95d800-69ba-11e9-8e0d-bd14a4046fbc.png)
请检查你的dotnet core sdk的版本号:
```shell
PS D:\workspace\SunWin.SRCC\src\nupkg> dotnet --list-sdks
2.1.600 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.2.101 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
```
我指定的版本是: "version": "2.2.102`的版本,如果不存在,請安裝該版本,或是透過修改[这里](https://github.com/liuhll/Surging.Sample/blob/3f4919546da9ed9460289d8c00dd2ad1c5bdf036/global.json#L3)指定你的版本号,但是必须要求:dotnet core的版本号为:`2.2`版本

**Comment by gxlqssjf** [comment]
![image](https://user-images.githubusercontent.com/1277598/56874901-b5788780-6a6f-11e9-8a6e-2cc229d278cf.png)
@liuhll

**Comment by gxlqssjf** [comment]
为什么要指定版本？？

**Comment by liuhll** [comment]
如果是团队项目的话，统一开发环境，避免因为环境的差异导致的不必要的bug的出现
