### ISSUE TITLE
请问下数据库链接在哪配置

### ISSUE THREAD

**Issue by keepRunM** [liuhll/Surging.Sample#5]
![image](https://user-images.githubusercontent.com/29815398/56860416-041f1680-69c9-11e9-8c3c-8f79a3c42338.png)

**Comment by liuhll** [comment]
你可以在[surgingSetting](https://github.com/liuhll/Surging.Sample/blob/3f4919546da9ed9460289d8c00dd2ad1c5bdf036/src/Shares/Configs/surgingSettings.json#L31 )的`dbSetting`节点配置数据库连接,但是一般得你可以通过环境变量`.env`来指定某个微服务组件的数据库配置。到生产环境你还需要对数据库进行加密处理哦

**Comment by keepRunM** [comment]
感谢回复，因为我是刚刚接触docker。服务在容器里跑起来后，就不知道怎么办了，我继续学习再说吧。谢谢你的Surging.Sample



------------------ 原始邮件 ------------------
发件人: "liuhongliang"<notifications@github.com>; 
发送时间: 2019年4月28日(星期天) 下午4:08
收件人: "liuhll/Surging.Sample"<Surging.Sample@noreply.github.com>; 
抄送: "四不青年"<411384073@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [liuhll/Surging.Sample] 请问下数据库链接在哪配置 (#5)




你可以在surgingSetting的dbSetting节点配置数据库连接,但是一般得你可以通过环境变量.env来指定某个微服务组件的数据库配置。到生产环境你还需要对数据库进行加密处理哦

**Comment by liuhll** [comment]
@keepRunM 你可以推荐你的小伙伴来给个star

**Comment by keepRunM** [comment]
一定一定



------------------ 原始邮件 ------------------
发件人: "liuhongliang"<notifications@github.com>; 
发送时间: 2019年4月28日(星期天) 下午4:20
收件人: "liuhll/Surging.Sample"<Surging.Sample@noreply.github.com>; 
抄送: "四不青年"<411384073@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [liuhll/Surging.Sample] 请问下数据库链接在哪配置 (#5)




@keepRunM 你可以推荐你的小伙伴来给个star
