### ISSUE TITLE
关于网关的问题

### ISSUE THREAD

**Issue by mgopen** [liuhll/Surging.Sample#8]
请教几个问题：
1. 网关里的OnAuthorization怎么只返回isSuccess = true？没看到有实现ValidateJwtAuthentication和ValidateAppSecretAuthentication这两个方法

2.这个例子里的token是采用api里参数方式来传递的吗？网关是否还没处理token的传递，还是通过哪种方式来获取payload？

**Comment by liuhll** [comment]
1. 登录成功返回的是:`LoginResult`,关于签发`token`的[请查看](https://github.com/liuhll/Surging.Sample/blob/c9b944afd40578219579a20c9eb0dc6224771be6/src/Core/Surging.Core.ApiGateWay/OAuth/Implementation/AuthorizationServerProvider.cs#L48)
登录请[查看](https://github.com/liuhll/Surging.Sample/blob/c9b944afd40578219579a20c9eb0dc6224771be6/src/Servers/Identity/Hl.Identity.Application/Authorization/AccountApplication.cs#L28)

2. 认证与授权统一在网关实现, 服务内部之间的通信没有实现认证与授权(当前可以自己重构),只是获取了token的`payload `,`payload`在服务之间是通过rpcparams进行传递的,微服务内部是通过`RpcContext`获取。
