### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by azkxysys521** [liuhll/Surging.Sample#9]
运行报错一直提示No such device or address

**Comment by liuhll** [comment]
你是否已经启动了中间件?请详细描述你运行的步骤

**Comment by azkxysys521** [comment]
已启动中间件，如图，然后在连接mysql的时候报错no such device or address




------------------ 原始邮件 ------------------
发件人: liuhongliang <notifications@github.com>
发送时间: 2019年5月7日 10:22
收件人: liuhll/Surging.Sample <Surging.Sample@noreply.github.com>
抄送: azkxysys521 <846131756@qq.com>, Author <author@noreply.github.com>
主题: 回复：[liuhll/Surging.Sample] 运行报错 (#9)




你是否已经启动了中间件?请详细描述你运行的步骤

**Comment by liuhll** [comment]
没有看到你的截图,你需要使用Navicat创建数据库,数据库连接方式请查看`readme.md`

**Comment by azkxysys521** [comment]
数据库已经配置完毕，报错信息如下：
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Object (DelegateActivator), Services = [Surging.Core.CPlatform.Routing.IServiceRouteManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope




------------------ 原始邮件 ------------------
发件人: "liuhongliang"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 下午4:00
收件人: "liuhll/Surging.Sample"<Surging.Sample@noreply.github.com>;
抄送: "李晓"<846131756@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [liuhll/Surging.Sample] 运行报错 (#9)




没有看到你的截图,你需要使用Navicat创建数据库,数据库连接方式请查看readme.md

**Comment by liuhll** [comment]
请确保你的consul中间件已经启动了 你可以通过`http://127.0.0.1:18500`查看是否已经启动了consul服务
